---
# handlers file for add_centos7_to_ad
- name: Restart sshd centos
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes

- name: Restart sssd centos
  systemd:
    name: sssd
    state: restarted
    daemon_reload: yes
