---
# tasks file for add_ubuntu_16_04_to_add
  - name: Install packages if they are not installed
    apt:
     name: "{{ item }}"
     state: present
    loop: "{{package_for_install_ubuntu}}"

  - name: Check if the instance in the Active Directory
    command: id {{ user_ad }}@{{ domain_ad }}
    register: result
    ignore_errors: yes

  - block:

    - name: Generate settings for krb.conf
      template:
        src: krb5.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'
        follow: yes

    - name: Join the instance to the Active Directory
      shell: echo {{ user_ad_password }} | realm join -U {{ user_ad }}@{{ DOMAIN_AD }} {{ domain_ad }} --verbose
      register: output

    - name: Result of joining
      debug:
        var: output.stderr
  
    when: result.rc != 0
  
  - name: Set the SSH service to allow password authentication
    replace:
     path: '/etc/ssh/sshd_config'
     regexp: '^#PasswordAuthentication yes'
     replace:  'PasswordAuthentication  yes'
     backup: yes
    notify: 'restart sshd'
    when: result_ssh.rc != 0

  - name: Change variable in sssd file
    lineinfile:
     dest: '/etc/sssd/sssd.conf'
     regexp: '^use_fully_qualified_names '
     line:  'use_fully_qualified_names = False'
    notify: 'restart sssd'

  - name: Change variable in sssd file
    lineinfile:
     dest: '/etc/sssd/sssd.conf'
     regexp: '^use_fully_qualified_names '
     line:  'use_fully_qualified_names = False'
    notify: 'restart sssd'

  - name: Specify in sssd file who may login
    lineinfile:
     path: '/etc/sssd/sssd.conf'
     state: present
     line:  "{{ ad_access_filter }}"
    notify: 'restart sssd'

  - name: Add comment to sudoers file and  validate with saving
    lineinfile:
      path: /etc/sudoers
      state: present
      line: '## Add the "AWS Delegated Administrators" group from the example.com domain.'
      validate: /usr/sbin/visudo -cf %s

  - name: Add permissions for AD users and validate savings
    lineinfile:
      path: /etc/sudoers
      state: present
      line: "{{ group_ad }}"
      validate: /usr/sbin/visudo -cf %s

  - name: Add permission to create home directory
    lineinfile:
      path: /etc/pam.d/common-session
      line: 'session required pam_mkhomedir.so skel=/etc/skel/ umask=0077'

  - name: Check if the host was added to AD
    command: id {{ user_ad }}@{{ domain_ad }}
    register: finish_result
    ignore_errors: yes

  - debug:
     msg:  "RESULT: Host {{ ansible_hostname }} with {{ ansible_default_ipv4.address }} was added to AD successfully"
    when: finish_result.rc == 0

  - debug:
     msg:  "RESULT: Host {{ ansible_hostname }} with {{ ansible_default_ipv4.address }} wasn't added to AD successfully"
    when: finish_result.rc != 0
