- name: Ensure that DNS1_prod and DNS2_prod set in dhclient.conf file 
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    regexp: 'supersede domain-name'
    line: 'supersede domain-name-servers {{ DNS1_prod }}, {{ DNS2_prod }};'
    state: present
  when: (DNS1_prod is defined) and (DNS2_prod is defined)
  register: out_dhcp_file

- name: Ensure that the variable PEERDNS set "yes" in ifcfg-{{ ansible_default_ipv4.interface }}   
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    regexp: '^PEERDNS'
    line: PEERDNS=yes
    state: present
  register: out_ifcfg_file

- name: Restart network centos
  systemd:
    name: network
    state: restarted
    daemon_reload: yes
  when: ( out_dhcp_file.changed == true ) or ( out_ifcfg_file.changed == true ) 

- name: Install packages 
  yum:
    name: ['sssd', 'realmd', 'krb5-workstation', 'samba-common-tools']
    state: present

- name: Check if the instance in production Active Directory
  command: id {{ user_ad }}@{{ domain_ad_prod }}
  register: result
  ignore_errors: yes
   
- block:
  - name: Join the instance to the production Active Directory
    shell: echo '{{ user_ad_password }}' | realm join -U {{ user_ad }}@{{ domain_ad_prod }} {{ domain_ad_prod }}  --verbose
    register: output

  - name: "Result of joining"
    debug:
      var: output.stderr

  - name: Generate SSSD file for Centos 
    template:
      src: sssd_centos_prod.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: '0600'
      force: yes
    notify: 
      - Restart sssd centos
  when: result.rc != 0

- name: Generate sudoers file for Centos
  template:
    src: sudoers_prod.j2
    dest: /etc/sudoers.d/sudoers_ad
    owner: root
    group: root
    mode: '0440'

- name: Set the PasswordAuthentication setting to yes in ssh config
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^PasswordAuthentication'
    line:  'PasswordAuthentication yes'
    state: present
  notify: 
    - Restart sshd centos

- name: Check if the host was added to the prodcution AD
  command: id {{ user_ad }}@{{ domain_ad_prod }}
  register: finish_result 
  ignore_errors: yes
  
- debug:
    msg:  "RESULT: Host {{ ansible_hostname }} with {{ ansible_default_ipv4.address }} was added to production AD successfully in production"
  when: finish_result.rc == 0 

- debug:
    msg:  "RESULT: Host {{ ansible_hostname }} with {{ ansible_default_ipv4.address }} wasn't added to AD successfully in production"
  when: finish_result.rc != 0
